#!/bin/bash
# Run test for 300 seconds
EXPIRES=300
END=120
IFACE=babel0
PROTO=8 # reuse gated for this sort of testing

#IPv6 Prefix generator intended to blow up routes everywhere
#Crudely but consistently generate a random prefix
#use the fc range to keep it clear

a=`hostname | md5sum`
prefix=fc${a:0:2}:${a:3:4}::

setup() {
ip link add $IFACE type dummy
ip link set $IFACE up
# Add a covering route to add to the fun
ip -6 route add $prefix/48 expires $EXPIRES proto $PROTO
}

teardown() {
ip link del $IFACE
}

add() {
for i in `seq 1 $END`
do
ip -6 route add `printf $P $i` dev $IFACE proto $PROTO expires $EXPIRES
done
}

del() {

ip -6 route flush dev $IFACE proto $PROTO

}

main() {
setup
add
sleep $EXPIRES
del
teardown
}

main
