#!/bin/bash
# Run test for 300 seconds
HOST=`hostname`
EXPIRES=300
END=120
IFACE=babel0
PROTO=8 # reuse gated for this sort of testing

#IPv6 Prefix generator intended to blow up routes everywhere
#Crudely but consistently generate a random PREFIX
#use the fc range to keep it clear

a=`echo $HOST | md5sum`

PREFIX=fc${a:0:2}:${a:3:4}:${a:8:4}::

echo $HOST has $PREFIX

export PREFIX PROTO IFACE END EXPIRES

setup() {
ip link add $IFACE type dummy
ip link set $IFACE up
# Add a covering route to add to the fun
ip -6 route add ${PREFIX}/48 expires $EXPIRES proto $PROTO
}

teardown() {
ip link del $IFACE
}

add() {
for i in `seq 1 $END`
do
ip -6 route add ${PREFIX}`printf %x $i` dev $IFACE proto $PROTO expires $EXPIRES
done
}

del() {

ip -6 route flush dev $IFACE proto $PROTO

}

main() {
setup
add
sleep $EXPIRES
del
teardown
}

main
